### ISSUE TITLE
padding bij

### ISSUE THREAD

**Issue by Theo-denBlanken** [Luseres/Responsive_grid#3]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/Luseres/Responsive_grid/blob/master/stijl.css

Feedback: header, aside en footer[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"f323bb1e47bd5a490dbe354b30035f8069e0b4a2","path":"stijl.css","reviewer":"Theo-denBlanken"}')

**Comment by Luseres** [comment]
Ok
